name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # каждый день в 00:00 UTC
  workflow_dispatch:       # запуск вручную

permissions:
  contents: write          # нужно, чтобы пушить ветку output

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Lumen161
          outputs: dist/github-contribution-grid-snake.svg

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
